version: '2'
services:
    protocolotap1-app:
        image: protocolotap1
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://protocolotap1-postgresql:5432/ProtocoloTAP1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    protocolotap1-postgresql:
        extends:
            file: postgresql.yml
            service: protocolotap1-postgresql
